#!/usr/bin/env python3
"""Generate the final HTML report and the generated documentation files.

Outputs:
  outputs/report/CNV_GIS_Data_Analysis_Report.html
  outputs/report/CNV_GIS_Data_Analysis_Report.pdf   (if a converter is available)
  DATA_SOURCES.md    (generated from config/sources.yaml + the download inventory)
"""
from __future__ import annotations

import html
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import geopandas as gpd
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import (  # noqa: E402
    DATA_PROCESSED,
    OUTPUTS,
    PROJECT_ROOT,
    get_logger,
    load_sources,
    load_study_area,
)

log = get_logger("20_generate_report")
REPORT = OUTPUTS / "report"
TABLES = OUTPUTS / "tables"


def esc(v) -> str:
    return html.escape("" if v is None or (isinstance(v, float) and pd.isna(v)) else str(v))


def df_to_html(df: pd.DataFrame, max_rows: int = 25) -> str:
    d = df.head(max_rows)
    head = "".join(f"<th>{esc(c)}</th>" for c in d.columns)
    rows = "".join(
        "<tr>" + "".join(f"<td>{esc(v)}</td>" for v in r) + "</tr>"
        for r in d.itertuples(index=False)
    )
    more = (f"<p class='muted'>Showing {max_rows} of {len(df):,} rows; "
            f"the full table is in outputs/tables/.</p>" if len(df) > max_rows else "")
    return f"<div class='tw'><table><thead><tr>{head}</tr></thead><tbody>{rows}</tbody></table></div>{more}"


def generate_data_sources_md() -> None:
    cfg = load_sources()
    inv_path = TABLES / "data_inventory.csv"
    inv = pd.read_csv(inv_path).set_index("source_id") if inv_path.exists() else pd.DataFrame()

    lines = [
        "# DATA_SOURCES.md — City of North Vancouver GIS Analysis",
        "",
        "Generated by `scripts/20_generate_report.py` from `config/sources.yaml` and the",
        "download inventory. Every endpoint listed here was probed live before use.",
        "",
        f"Generated: {datetime.now(timezone.utc).date().isoformat()}",
        "",
        "## Source inventory",
        "",
        "| source_id | organization | dataset | format | geographic level | coverage | licence | status | records |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for s in cfg["sources"]:
        sid = s["source_id"]
        row = inv.loc[sid] if sid in inv.index else None
        status = row["status"] if row is not None else "not downloaded"
        n = ""
        if row is not None and pd.notna(row.get("feature_count")) and row.get("feature_count") != "":
            n = f"{row['feature_count']}"
        elif row is not None and pd.notna(row.get("bytes")):
            try:
                n = f"{int(float(row['bytes']))/1e6:.1f} MB"
            except (TypeError, ValueError):
                n = ""
        lines.append(
            f"| `{sid}` | {s.get('organization','')} | {s.get('dataset','')} | "
            f"{s.get('format','')} | {s.get('geographic_level','')} | {s.get('coverage','')} | "
            f"{s.get('license','see provider')} | {status} | {n} |"
        )

    lines += ["", "## Endpoints", ""]
    for s in cfg["sources"]:
        lines.append(f"### `{s['source_id']}`")
        lines.append(f"- **Dataset:** {s.get('dataset','')}")
        lines.append(f"- **Organization:** {s.get('organization','')}")
        lines.append(f"- **Landing page:** {s.get('url','')}")
        if s.get("download_url"):
            lines.append(f"- **Download URL:** `{s['download_url']}`")
        if s.get("service"):
            lines.append(f"- **ArcGIS service:** `{s['service']}` layer `{s.get('layer_id')}`")
        if s.get("typename"):
            lines.append(f"- **WFS typeName:** `{s['typename']}`")
        if s.get("cql_filter"):
            lines.append(f"- **CQL filter:** `{s['cql_filter']}`")
        lines.append(f"- **Licence:** {s.get('license','see provider terms')}")
        if s.get("notes"):
            lines.append(f"- **Notes:** {' '.join(str(s['notes']).split())}")
        lines.append("")

    (PROJECT_ROOT / "DATA_SOURCES.md").write_text("\n".join(lines), encoding="utf-8")
    log.info("wrote DATA_SOURCES.md (%d sources)", len(cfg["sources"]))


def main() -> int:
    cfg = load_study_area()
    REPORT.mkdir(parents=True, exist_ok=True)
    generate_data_sources_md()

    census = gpd.read_file(DATA_PROCESSED / "cnv_census_2021.gpkg", layer="cnv_census_da")
    nbs = gpd.read_file(DATA_PROCESSED / "cnv_neighbourhoods_stats.gpkg",
                        layer="cnv_neighbourhoods_stats")
    scores = gpd.read_file(DATA_PROCESSED / "cnv_public_space_scores.gpkg",
                           layer="public_space_scores")
    roads = gpd.read_file(DATA_PROCESSED / "cnv_roads.gpkg", layer="roads")
    stops = gpd.read_file(DATA_PROCESSED / "cnv_transit.gpkg", layer="transit_stops")
    occ = gpd.read_file(DATA_PROCESSED / "cnv_parking.gpkg", layer="parking_occupancy")
    inv = pd.read_csv(TABLES / "data_inventory.csv")
    gaps = pd.read_csv(TABLES / "data_gaps.csv")
    turnout = pd.read_csv(TABLES / "election_turnout_series.csv")
    places = pd.read_csv(TABLES / "polling_location_summary.csv")

    pop = census["population_2021"].sum()
    adults = census["adult_population_18plus_proxy"].sum()
    citizens = census["canadian_citizens_18plus"].sum()
    seniors = census["senior_population_65plus"].sum()
    dwellings = census["occupied_private_dwellings"].sum()
    land = census["land_area_km2"].sum()
    reg2022 = float(turnout[turnout["year"] == 2022]["registered_voters"].iloc[0])
    top = scores.nsmallest(20, "composite_rank")

    maps = sorted((OUTPUTS / "maps").glob("*.png"))
    map_html = "".join(
        f"<figure><img src='../maps/{m.name}' alt='{esc(m.stem)}'>"
        f"<figcaption>{esc(m.stem.replace('_',' '))}</figcaption></figure>"
        for m in maps
    )

    gap_rows = "".join(
        f"<tr><td>{esc(r['gap_id'])}</td><td>{esc(r['dataset'])}</td>"
        f"<td><span class='sev sev-{esc(str(r['severity']).lower())}'>{esc(r['severity'])}</span></td>"
        f"<td>{esc(r['best_proxy_used'])}</td><td>{esc(r['coverage_achieved'])}</td></tr>"
        for _, r in gaps.iterrows()
    )

    doc = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>City of North Vancouver — GIS Data Analysis Report</title>
<style>
:root{{--fg:#1a1a1a;--muted:#5f6b76;--line:#e3e7ea;--accent:#0b6e99;--warn:#c1121f;--bg:#fff}}
*{{box-sizing:border-box}}
body{{margin:0;font:16px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Georgia,serif;color:var(--fg);background:var(--bg)}}
.wrap{{max-width:1080px;margin:0 auto;padding:48px 28px 90px}}
h1{{font-size:34px;line-height:1.2;margin:0 0 6px}}
h2{{font-size:24px;margin:52px 0 12px;padding-bottom:7px;border-bottom:2px solid var(--line)}}
h3{{font-size:18px;margin:30px 0 8px}}
.lede{{font-size:18px;color:var(--muted);margin:0 0 26px}}
.muted{{color:var(--muted);font-size:13.5px}}
.kpis{{display:grid;grid-template-columns:repeat(auto-fit,minmax(168px,1fr));gap:13px;margin:26px 0}}
.kpi{{border:1px solid var(--line);border-radius:9px;padding:14px 16px}}
.kpi .n{{font-size:26px;font-weight:700;letter-spacing:-.02em}}
.kpi .l{{font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:.05em;margin-top:3px}}
.tw{{overflow-x:auto;margin:14px 0}}
table{{border-collapse:collapse;width:100%;font-size:13.5px}}
th,td{{text-align:left;padding:7px 11px;border-bottom:1px solid var(--line);vertical-align:top}}
th{{background:#f6f8f9;font-weight:600;white-space:nowrap}}
.note{{border-left:4px solid var(--accent);background:#f4f9fc;padding:13px 17px;margin:18px 0;border-radius:0 6px 6px 0;font-size:14.5px}}
.warn{{border-left-color:var(--warn);background:#fdf4f4}}
figure{{margin:26px 0}} figure img{{width:100%;border:1px solid var(--line);border-radius:7px}}
figcaption{{font-size:13px;color:var(--muted);margin-top:7px}}
.sev{{padding:2px 8px;border-radius:11px;font-size:11.5px;font-weight:600;white-space:nowrap}}
.sev-high{{background:#fde2e2;color:#8b1a1a}} .sev-medium{{background:#fdf0d5;color:#8a5a00}}
.sev-low{{background:#e6f4ea;color:#1d6b33}} .sev-structural{{background:#e8e6fd;color:#3b2f8a}}
.sev-resolved{{background:#e6f4ea;color:#1d6b33}}
code{{background:#f2f4f5;padding:1.5px 5px;border-radius:4px;font-size:13px}}
ol.toc{{columns:2;font-size:14.5px}} ol.toc li{{margin:3px 0;break-inside:avoid}}
@media print{{.wrap{{max-width:none}} h2{{page-break-after:avoid}} figure{{page-break-inside:avoid}}}}
</style></head><body><div class="wrap">

<h1>City of North Vancouver — GIS Data Analysis Report</h1>
<p class="lede">A reproducible civic-geography analysis of population, housing, transportation
and public space in the City of North Vancouver, British Columbia.</p>
<p class="muted">Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} ·
Analysis CRS EPSG:26910 (NAD83 / UTM zone 10N) · Census year 2021 ·
Study area CSDUID 5915051</p>

<div class="note warn">
<strong>Terminology and scope.</strong> Population aged 18+ is reported as
<code>adult_population_18plus_proxy</code>, a demographic proxy for potential electorate
size. It is <em>not</em> a count of eligible or registered electors. This report contains no
individual-level data, and the public-space score contains no political variable of any
kind and makes no inference from demographics to political preference.
</div>

<h2>1. Executive summary</h2>
<div class="kpis">
<div class="kpi"><div class="n">{pop:,.0f}</div><div class="l">Population 2021</div></div>
<div class="kpi"><div class="n">{adults:,.0f}</div><div class="l">Adults 18+ (proxy)</div></div>
<div class="kpi"><div class="n">{citizens:,.0f}</div><div class="l">Citizens 18+</div></div>
<div class="kpi"><div class="n">{seniors:,.0f}</div><div class="l">Seniors 65+</div></div>
<div class="kpi"><div class="n">{dwellings:,.0f}</div><div class="l">Occupied dwellings</div></div>
<div class="kpi"><div class="n">{pop/land:,.0f}</div><div class="l">Persons / km²</div></div>
<div class="kpi"><div class="n">{len(census)}</div><div class="l">Dissemination areas</div></div>
<div class="kpi"><div class="n">{len(scores)}</div><div class="l">Intersections scored</div></div>
</div>

<p>The City of North Vancouver houses {pop:,.0f} residents on {land:.2f} km² of land, giving
an overall density of {pop/land:,.0f} persons per km² — among the highest in the province
outside the City of Vancouver. It is overwhelmingly a multi-unit city:
{100*census['multiunit_dwellings'].sum()/census['dwellings_by_structure_total'].sum():.1f}%
of occupied private dwellings are apartments, row houses or duplexes, and only
{100*census['dw_single_detached'].sum()/census['dwellings_by_structure_total'].sum():.1f}%
are single-detached.</p>

<p>Density is concentrated sharply along the Lonsdale Avenue spine. Lower Lonsdale and
Central Lonsdale together hold
{100*(nbs.set_index('neighbourhood').loc[['Lower Lonsdale','Central Lonsdale'],'population_2021'].sum())/pop:.0f}%
of the city's population on a small fraction of its land, and the highest-density
dissemination area reaches {census['population_density'].max():,.0f} persons per km².
The same corridor dominates the public-space analysis: the twenty highest-scoring
intersections are almost all on or adjacent to Lonsdale Avenue.</p>

<p>A notable validation emerged from the electoral analysis. The 2021 Census counted
{citizens:,.0f} Canadian citizens aged 18 and over in the city, while the City recorded
{reg2022:,.0f} registered electors for the 2022 general local election — a difference of
{100*abs(citizens-reg2022)/reg2022:.1f}%. This is a useful consistency check on the
citizenship-based proxy, though the two measures are not the same thing and are not
presented as such.</p>

<h2>2. Contents</h2>
<ol class="toc">
<li>Executive summary</li><li>Contents</li><li>Study area</li><li>Data sources</li>
<li>Data acquisition</li><li>Data cleaning and validation</li><li>Census methodology</li>
<li>Housing methodology</li><li>Electoral and polling methodology</li>
<li>Transportation methodology</li><li>Traffic methodology</li><li>Transit methodology</li>
<li>Parking methodology</li><li>Safety and visibility methodology</li><li>GIS methods</li>
<li>Results</li><li>Ranked tables</li><li>Maps</li><li>Data limitations</li>
<li>Privacy and ethics</li><li>Reproducibility</li>
</ol>

<h2>3. Study area</h2>
<p>The study area is the <strong>City of North Vancouver</strong> (BC ABMS
<code>LGL_ADMIN_AREA_ID = 114</code>; Statistics Canada <code>CSDUID 5915051</code>, type CY).
It is deliberately distinguished from the District of North Vancouver
(<code>5915046</code>, type DM), the North Vancouver electoral districts, Metro Vancouver
and the informal "North Shore".</p>

<div class="note">
<strong>Legal boundary versus land area.</strong> The BC ABMS legal boundary encloses
14.92 km² because it extends into Burrard Inlet. Statistics Canada reports the city's land
area as 11.83 km², and the 79 constituent dissemination areas sum to {land:.2f} km².
<strong>All densities in this report divide by land area</strong>, never the legal boundary
area. Using the legal boundary would understate density by roughly 26%.
</div>

<h2>4. Data sources</h2>
<p>{len(inv)} sources were audited and downloaded. The complete inventory with endpoints,
licences and SHA256 hashes is in <code>DATA_SOURCES.md</code> and
<code>outputs/tables/data_inventory.csv</code>.</p>
{df_to_html(inv[['source_id','organization','dataset','format','status']], 20)}

<h3>Principal sources</h3>
<ul>
<li><strong>Statistics Canada</strong> — 2021 Census Profile 98-401-X2021006, British
Columbia dissemination-area file (the BC-only comprehensive CSV, 293 MB, rather than the
2.2 GB national file), plus the 2021 DA, DB and CSD cartographic boundary files.</li>
<li><strong>City of North Vancouver</strong> — the public ArcGIS REST server at
<code>gisext2.cnv.org</code>, whose <code>TransportMAP</code> service alone exposes 230
layers covering roads, signals, parking, sidewalks, zoning and land use.</li>
<li><strong>Province of BC</strong> — ABMS legal municipal boundaries via WFS; BC MoTI
traffic count stations via the GeoServer WFS at <code>maps.th.gov.bc.ca/geoV05/ows</code>.</li>
<li><strong>TransLink</strong> — GTFS static feed for transit stops, routes and frequency.</li>
<li><strong>ICBC</strong> — Lower Mainland crash counts via the Tableau Public dashboard's
own CSV export.</li>
</ul>

<h2>5. Data acquisition</h2>
<p><code>scripts/01_download.py</code> reads <code>config/sources.yaml</code> and downloads
every source into <code>data/raw/</code>. Raw files are never overwritten unless
<code>--force</code> is given. Each download receives a SHA256 hash and a
<code>.meta.json</code> sidecar recording the source URL, licence, retrieval timestamp and
record count. Downloads are validated so that an HTML error page cannot masquerade as a ZIP
or CSV.</p>
<p>Two acquisition problems were encountered and resolved rather than worked around. The
CNV road-classification layer contains eleven features the ArcGIS endpoint cannot
serialise; the downloader bisects around them, retrieving 507 of 518 and recording the
unreadable OBJECTIDs. Separately, the GEOweb download URL pattern initially assumed was
wrong and was corrected against the page's own HTML before any run.</p>

<h2>6. Data cleaning and validation</h2>
<p><code>scripts/02_validate_sources.py</code> re-hashes every raw file, verifies container
integrity and confirms that vector payloads parse and carry a CRS. All {len(inv)} sources
validate. The automated QA suite in <code>tests/</code> then enforces CRS consistency,
geometry validity, identifier uniqueness, population plausibility, spatial containment and
the project's privacy and terminology constraints.</p>

<div class="note">
<strong>Validation that changed a result.</strong> The parking occupancy layer pairs an
occupied-vehicle count with a published percentage for each surveyed period, but the field
naming differs between weekday and weekend blocks. An initial pairing agreed with the
City's published percentages for only 71–78% of segments. Investigation showed the pairing
was in fact correct and the disagreement was one-vehicle rounding on very short segments,
where <code>Supply</code> is a small integer estimate of a continuous capacity. With a
tolerance of one vehicle on the segment's own supply, agreement is 99.8–100%. The City's
published percentage is used as authoritative and the recomputed ratio is retained as a
cross-check.
</div>

<h2>7. Census methodology</h2>
<p>The BC dissemination-area Census Profile is a 3.6 GB long-format CSV. Rather than parse
it in full, the pipeline uses Statistics Canada's own line-number index to seek directly to
the 79 CNV dissemination areas, extracting them in about ten seconds. Every extracted row is
verified against <code>ALT_GEO_CODE</code> to prove the index alignment is correct — an
off-by-one at the block boundary was caught this way.</p>
<p>DA membership in the city is determined by representative-point containment within the
CNV census subdivision polygon, because the cartographic DA file carries no CSDUID. The
result reconciles exactly with the published CSD totals: population {pop:,.0f} against
58,120 published, and occupied private dwellings {dwellings:,.0f} against 27,293 published.</p>

<h3>The 18+ proxy</h3>
<p>The Census publishes ages 15–19 as a single band, so the 18–19 portion is apportioned as
two-fifths of that band under a uniform-age assumption:</p>
<p><code>adult_population_18plus_proxy = population_2021 − age_0_14 − (3/5 × age_15_19)</code></p>
<p>A second and closer measure, <code>canadian_citizens_18plus</code>, is taken directly from
the Census citizenship table. Because BC municipal elections require Canadian citizenship,
this is materially closer to elector eligibility, and it lands within
{100*abs(citizens-reg2022)/reg2022:.1f}% of the official registered-elector count. Neither
field is ever labelled "eligible voters"; an automated test fails the build if that term
appears as a column anywhere in the outputs.</p>

<h2>8. Housing methodology</h2>
<p>Dwelling structure type comes from the Census at DA level and is complete. Building-level
attributes are not: the City's 11,833 footprints carry only status and name, and only the
separate high-rise layer publishes height, unit counts and year built. Coverage is therefore
0.9% for height, 0.7% for unit counts and 0.9% for year built. Buildings are classified from
published evidence only, with the evidence recorded in
<code>classification_basis</code>; 98.6% are honestly labelled <code>UNKNOWN</code>, which
means the City publishes nothing about them, not that they are non-residential.</p>
<p>Condominium tenure is recorded <em>only</em> where the City's own <code>Occupancy</code>
attribute contains <code>STRATA</code>. It is never inferred from building form or height.</p>

<h2>9. Electoral and polling methodology</h2>
<p>All electoral figures are aggregate and officially published. CNV runs
<strong>"any voting place" elections</strong>: an elector may vote at any location in the
city. There are therefore no polling-division catchments, and no polling-division boundary
dataset exists in any format — a structural absence rather than a data gap that could be
filled.</p>
{df_to_html(turnout[['year','registered_voters','turnout_pct']].head(10), 10)}
<p>Votes by voting place are published for 2022 and are included, but because electors may
vote anywhere, <strong>votes cast at a place cannot be attributed to residents near that
place</strong>. Resident counts within 400/800/1600 m of each voting place are provided as
context only.</p>
{df_to_html(places[['rank','place_name','address','place_type','mayoral_votes_2022']], 12)}

<h2>10–14. Transportation, traffic, transit, parking, safety</h2>
<p>The road network comprises {len(roads)} centreline segments totalling
{roads['length_m'].sum()/1000:.0f} km. Intersections are derived by clustering centreline
endpoints at a 5 m tolerance; a node qualifies when it joins two or more distinct street
names or three or more segment ends. This yields {len(scores)} intersections, of which 91%
lie within 25 m of an intersection in the independently published District of North
Vancouver GEOweb intersection layer — a strong external validation.</p>
<p><strong>Traffic.</strong> No AADT is published for any CNV municipal street. The BC
Traffic Data Program covers provincial highways only, and its ten in-city stations are all
on Highway 1 with counts no more recent than 2016. The City publishes directional volumes
for just 38 of 941 segments. Only 40 of {len(scores)} intersections have a measured volume
within the 150 m association distance, so <code>traffic_score</code> is primarily a
road-hierarchy measure and is labelled as such.</p>
<p><strong>Signals.</strong> The signal layer is a pole/asset inventory of 569 assets, not a
list of intersections. Clustering at 40 m yields 133 signalised locations, of which 79 have
at least one Full Signal and 54 are pedestrian-signal or special-crosswalk only. No cycle
length or phase timing is published anywhere; the City releases it on request. Every
signalised location carries <code>signal_timing_status = REQUEST_REQUIRED</code> and
<strong>no timing value is estimated</strong>.</p>
<p><strong>Transit.</strong> {len(stops[stops['in_cnv']]) if 'in_cnv' in stops else len(stops)}
TransLink stops lie inside the city, carrying
{int(stops[stops['in_cnv']]['trips_per_weekday'].sum()) if 'in_cnv' in stops else 0:,}
scheduled departures on a representative weekday across 15 routes.</p>
<p><strong>Parking.</strong> {len(occ):,} on-street segments were surveyed across eight time
periods, with a total supply of {occ['supply_spaces'].sum():,.0f} spaces.
{occ['at_practical_capacity'].sum():,} segments ({100*occ['at_practical_capacity'].mean():.0f}%)
reach 85% occupancy or more at some point. This is <strong>survey data collected by Bunt &amp;
Associates in December 2022 and January–February 2023</strong>, not a real-time feed.</p>
<p><strong>Safety.</strong> ICBC publishes crash counts against location name strings with no
coordinates, and its "NORTH VANCOUVER" value covers both the City and the District.
Attribution required at least two named CNV streets forming a pair present in the CNV
intersection layer, matching 288 intersections and 5,296 crashes. Intersections without a
match are recorded as <strong>unknown, not zero</strong>, and receive no safety score.</p>

<h2>15. GIS methods</h2>
<p>All analysis is performed in EPSG:26910 (NAD83 / UTM zone 10N), the CNV server's native
projected CRS, so areas and distances are metric throughout. EPSG:4326 is used only for web
export; no area or distance is ever computed in degrees. Population within intersection
buffers is areally interpolated from dissemination areas, which assumes uniform distribution
within each DA — recorded on the output layer as an estimate, not a count.</p>

<h2>16. Results — the public-space score</h2>
<p>The score is a neutral measure of how visible, accessible and feasible each intersection
is as a public space. Seven components are computed as 0–100 percentile ranks and kept
separate; the composite is their unweighted mean. Missing inputs stay missing rather than
scoring as zero.</p>
{df_to_html(top[['composite_rank','street_names','neighbourhood','public_space_composite',
                 'traffic_score','transit_score','pedestrian_proxy_score',
                 'parking_access_score','safety_score']], 20)}

<h3>Neighbourhood profile</h3>
{df_to_html(nbs.drop(columns='geometry')[['neighbourhood','population_2021',
    'adult_population_18plus_proxy','senior_population_65plus','population_density',
    'housing_density','apartment_share']].sort_values('population_2021', ascending=False), 12)}

<h2>17. Ranked tables</h2>
<p>Every ranking table carries rank, feature identifier, metric, value, source and a
methodology note. All are in <code>outputs/tables/</code> and are downloadable from the
interactive map.</p>

<h2>18. Maps</h2>
{map_html}

<h2>19. Data limitations</h2>
<p>Thirteen gaps are documented in full in <code>DATA_GAPS.md</code>. The three that most
constrain interpretation are the absence of municipal traffic counts, the absence of any
published signal timing, and the absence of pedestrian counts.</p>
<div class="tw"><table><thead><tr><th>#</th><th>Dataset</th><th>Severity</th>
<th>Proxy used</th><th>Coverage achieved</th></tr></thead><tbody>{gap_rows}</tbody></table></div>

<h2>20. Privacy and ethical considerations</h2>
<ul>
<li>No individual-level data of any kind is collected, derived or stored. The smallest
geography used is the dissemination area or block.</li>
<li>No voter identity, address, contact detail or political preference is collected. Only
aggregate published election results are used.</li>
<li>Population aged 18+ is a demographic proxy and is never described as eligible or
registered electors. The field name <code>adult_population_18plus_proxy</code> is enforced
by an automated test, as is the absence of the term "eligible voters" from all outputs.</li>
<li>The public-space score contains no political variable — no party, candidate or voting
history — and makes no inference from demographics to political preference. A test asserts
that no such field exists.</li>
<li>Because CNV electors may vote at any location, votes at a voting place are never
attributed to the residents living near it.</li>
<li>No dataset was obtained by bypassing authentication, CAPTCHAs, rate limits or robots
restrictions. Where a source was unavailable by those means (CivicInfo BC's bot challenge,
VCH's directory) it was recorded as unavailable rather than circumvented.</li>
</ul>

<h2>21. Reproducibility</h2>
<p>The full pipeline runs with <code>python run_pipeline.py --all</code>, or stage by stage
from <code>scripts/01_download.py</code> through <code>scripts/20_generate_report.py</code>.
Raw downloads are cached and hash-verified, so re-runs are deterministic given stable
upstream sources. Run <code>python -m pytest</code> before regenerating this report.</p>

<p class="muted" style="margin-top:44px;border-top:1px solid var(--line);padding-top:16px">
Contains information licensed under the Statistics Canada Open Licence, the Open Government
Licence – British Columbia, the Open Data Licence for ICBC Information, City of North
Vancouver open data terms and TransLink's GTFS terms of use. See
<code>LICENSES_AND_ATTRIBUTION.md</code>.</p>

</div></body></html>"""

    out = REPORT / "CNV_GIS_Data_Analysis_Report.html"
    out.write_text(doc, encoding="utf-8")
    log.info("wrote %s (%.0f KB)", out, out.stat().st_size / 1024)

    # Optional PDF. Prefer the WeasyPrint Python API, which resolves the relative map
    # image paths via base_url; fall back to a CLI converter if one is installed.
    pdf = REPORT / "CNV_GIS_Data_Analysis_Report.pdf"
    try:
        import weasyprint  # noqa: PLC0415

        weasyprint.HTML(filename=str(out), base_url=str(out.parent)).write_pdf(str(pdf))
        log.info("wrote %s (%.1f MB) via WeasyPrint", pdf, pdf.stat().st_size / 1e6)
        return 0
    except ImportError:
        log.info("WeasyPrint not installed; trying a CLI converter")
    except Exception as exc:  # noqa: BLE001
        log.warning("WeasyPrint failed: %s", exc)

    if shutil.which("wkhtmltopdf"):
        try:
            subprocess.run(["wkhtmltopdf", "--enable-local-file-access", str(out), str(pdf)],
                           check=True, capture_output=True, timeout=300)
            log.info("wrote %s via wkhtmltopdf", pdf)
            return 0
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
            log.warning("wkhtmltopdf failed: %s", exc)

    log.info("no HTML-to-PDF converter available; HTML report only "
             "(pip install weasyprint to enable PDF output)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
